theme = "rose_pine_moon"

[editor]
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
line-number = "relative"
popup-border = "none"
trim-trailing-whitespace = true
trim-final-newlines = true
insert-final-newline = true

# [editor.lsp]
# display-inlay-hints = true

[editor.soft-wrap]
enable = false

[editor.statusline]
left = ["mode", "version-control"]
center = ["file-name"]
right = ["diagnostics", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.file-picker]
# hidden = false
# git-ignore = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

# Keymaps #

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
'=' = ":format"

[keys.normal.space.t]
b = ":echo %sh{$HOME/.config/helix/scripts/pretty_blame.sh %{buffer_name} %{cursor_line}}"

[keys.normal.space.h]
p = ":sh $HOME/.config/helix/scripts/preview_hunk.sh %{buffer_name} %{cursor_line} 0"
r = ":reset-diff-change"

# does work, but helix doesnt display staged hunks differently,
# at least I couldnt notice any difference :(
s = ":echo %sh{$HOME/.config/helix/scripts/stage_hunk.sh %{buffer_name} %{cursor_line} 0}"

[keys.normal]
S-right = "move_next_word_start"
S-left = "move_prev_word_end"
S-down = "page_cursor_half_down"
S-up = "page_cursor_half_up"

[keys.insert]
S-right = "move_next_word_start"
S-left = "move_prev_word_end"
S-down = "page_cursor_half_down"
S-up = "page_cursor_half_up"

[keys.select]
S-right = "extend_next_word_start"
S-left = "extend_prev_word_end"
S-down = "page_cursor_half_down"
S-up = "page_cursor_half_up"
