# LSP configs #

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "off"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]
run = "onSave"

# [language-server.pyrefly]
# command = "pyrefly"
# args = ["lsp"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
dialect = "British"

[language-server.harper-ls.config.harper-ls.linters]
SentenceCapitalization = false

[language-server.swiftlint]
command = "swiftlint"

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
typstExtraArgs = ["main.typ"]

# Language configs #

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
# language-servers = [ "pyrefly", "ruff" ]

[[languages]]
name = "go"
auto-format = false
formatter = { command = "goimports" }

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts"]
auto-format = false
language-servers = ["deno-lsp"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]
block-comment-tokens = {start = "<!--", end = "-->"}

[[language]]
name = "swift"
auto-format = true
language-servers = ["sourcekit-lsp", "swiftlint"]

[[language]]
name = "typst"
auto-format = true
soft-wrap = { enable = true }
formatter.command = "typstyle"
language-servers = ["tinymist", "harper-ls"]

[[language]]
name = "markdown"
soft-wrap = { enable = true }
language-servers = ["marksman", "harper-ls"]
